import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const Circular_Std = localFont({ src: "./CircularStd-Book.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Circular_Std.className}>{children}</body>
    </html>
  );
}
